context:
  name: scifem
  version: "0.5.0"
  fenics_version: "0.9.*"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/scifem/scifem-${{ version }}.tar.gz
  sha256: 0b54bb895790beb00d87f04084ff5ed300e2806f0799bf6423c3cb5c583d5ed7

build:
  number: 1
  skip:
    - win
    - match(python, "<3.10")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - if: build_platform != target_platform
      then:
        - if: mpi == 'openmpi'
          then: ${{ mpi }}
        - cross-python_${{ target_platform }}
        - python
        - nanobind
  host:
    - fenics-libbasix ${{ fenics_version }}
    - fenics-basix ${{ fenics_version }}
    - fenics-libdolfinx ${{ fenics_version }}
    - fenics-dolfinx ${{ fenics_version }}

    # place adios2 in host environment to ensure
    # a compatible set of dependencies is pinned
    # (usually on hdf5)
    # run_exports are then ignored because we don't actually need
    # to pin adios2
    - adios2 * mpi_${{ mpi }}_*

    - ${{ mpi }}
    - petsc
    - petsc * ${{ scalar }}_*
    - pip
    - python
    - scikit-build-core
    - nanobind
  run:
    - python
    - fenics-basix
    - fenics-dolfinx
    - packaging
    - adios2 * mpi_${{ mpi }}_*
  run_constraints:
    # require mpi build of h5py
    - h5py * mpi_${{ mpi }}_*
  ignore_run_exports:
    # lose build-time pinning since we don't link libadios
    from_package:
      - adios2

tests:
  - python:
      imports:
        - scifem
      pip_check: true
  - files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - pytest
        - petsc4py
        # can't test h5py 
        # until it gets builds for hdf5 1.14.4
        # - h5py
    script:
      - pytest -vs tests
      - MPIEXEC_TIMEOUT=600 mpiexec -n 2 pytest -m "not serial" tests

about:
  summary: Scientific Computing Tools for Finite Element Methods
  description: |
    This package contains a collection of tools for scientific computing with a focus on finite element methods.
    The tools are written in Python and are intended to be used in conjunction with the dolfinx.
  license: MIT
  license_file: LICENSE
  homepage: https://scientificcomputing.github.io/scifem
  repository: https://github.com/scientificcomputing/scifem
  documentation: https://scientificcomputing.github.io/scifem

extra:
  recipe-maintainers:
    - finsberg
    - jorgensd
    - minrk
