context:
  name: scifem
  version: 0.2.8
  fenics_version: "0.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/s/scifem/scifem-${{ version }}.tar.gz
  sha256: 39b2cac1517a0284dcf38ffc49f5ef1bf86f7ffc67c9bb2d8d52236980fc2776

build:
  number: 2
  skip:
    - win
    - match(python, "<3.10")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - if: mpi == 'openmpi' and build_platform != target_platform
      then: ${{ mpi }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - nanobind
  host:
    - fenics-libbasix ${{ fenics_version }}
    - fenics-basix ${{ fenics_version }}
    - fenics-libdolfinx ${{ fenics_version }}
    - fenics-dolfinx ${{ fenics_version }}
    - ${{ mpi }}
    - petsc
    - petsc * ${{ scalar }}_*
    - pip
    - python
    - scikit-build-core
    - nanobind
  run:
    - python
    - fenics-basix
    - fenics-dolfinx
    - packaging
    - adios2 * mpi_${{ mpi }}_*
  run_constraints:
    # require mpi build of h5py
    - h5py * mpi_${{ mpi }}_*

tests:
  - python:
      imports:
        - scifem
      pip_check: true
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - petsc4py
        - h5py
    script:
      - pwd
      - ls -la
      - pytest -vs tests
      - if: "mpi != 'openmpi'"
        then: MPIEXEC_TIMEOUT=300 mpiexec -n 2 pytest -m "not serial" tests
      - if: "mpi == 'openmpi'"
        then: mpiexec --timeout=300 -n 2 pytest -m "not serial" tests

about:
  summary: Scientific Computing Tools for Finite Element Methods
  description: |
    This package contains a collection of tools for scientific computing with a focus on finite element methods.
    The tools are written in Python and are intended to be used in conjunction with the dolfinx.
  license: MIT
  license_file: LICENSE
  homepage: https://scientificcomputing.github.io/scifem
  repository: https://github.com/scientificcomputing/scifem
  documentation: https://scientificcomputing.github.io/scifem

extra:
  recipe-maintainers:
    - finsberg
    - jorgensd
    - minrk
